AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Events Stack

# -------------------------------------------

# Parameters:

# -------------------------------------------

Resources:
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSEventsLambdaExecutionRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal: 
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # -------------------------------------------
  # 
  # CloudWatchReceiver:
  #   Type: SNS::Topic
  #   Properties:
  #     Name: Recieve_CloudWatch2
  # 
  # CloudWatchHandler:
  #   Type: AWS::Lambda::Function
  #   Properties: 
  #     Code: components/
  #     Description: handler for CloudWatch events
  #     FunctionName: Handle_CloudWatch
  #     Handler: handlers/Handle_Watch.handler
  #     Role: !Ref LambdaExecutionRole
  #     Runtime: python3.6
  #     MemorySize: 128
  #     Timeout: 10
  # 
  # CloudWatchSubscription:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     Protocol: lambda
  #     Endpoint: !Ref CloudWatchHandler
  #     TopicArn: !Ref CloudWatchReceiver

  # -------------------------------------------
  
  # RDS_Receiver
  # RDS_Handler
  # RDS_Subscription
  
  # -------------------------------------------
  
  # Email_Notifier:
    # Type: Lambda