AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Events Stack

# -------------------------------------------

# Parameters:

# -------------------------------------------

Resources:
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSEventsLambdaExecutionRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal: 
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # -------------------------------------------
  
  CloudWatchHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code: components/
      Description: handler for CloudWatch events
      FunctionName: Handle_CloudWatch
      Handler: handlers/Handle_CloudWatch.handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  CloudWatchReceiver:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Receive_CloudWatch
      Subscription:
        - Protocol: lambda
          Endpoint:
            Fn::GetAtt:
              - CloudWatchHandler
              - Arn

  # -------------------------------------------

  CloudFormationHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code: components/
      Description: handler for CloudFormation events
      FunctionName: Handle_CloudFormation
      Handler: handlers/Handle_Formation.handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  CloudFormationReceiver:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Receive_CloudFormation
      Subscription:
        - Protocol: lambda
          Endpoint:
            Fn::GetAtt:
              - CloudFormationHandler
              - Arn
              
  # -------------------------------------------
  
  # RDS_Receiver
  # RDS_Handler
  # RDS_Subscription
  
  # -------------------------------------------
  
  # Email_Notifier:
    # Type: Lambda